name: ecom-micro

services:
  auth-db:
    container_name: auth-db
    image: postgres:16.3-alpine3.20
    volumes:
      - auth-data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
    ports:
      - "5432:5432"
    expose:
      - "5432"
  pgadmin:
    container_name: ecom-micro-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root@pass
    ports:
      - "6969:80"
  ecom-consul:
    container_name: ecom-consul
    image: consul:1.15.4
    volumes:
      - consul-data-volume:/var/lib/consul/data
    ports:
      - "8500:8500"
    networks:
      - ecom-network
  ecom-auth:
    build:
      context: ../services/auth  # This should point to the auth directory
      dockerfile: deployment/Dockerfile  # Specify the path to the Dockerfile
    ports:
      - "8099:8099"
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge

volumes:
  auth-data-volume:
    driver: local
  consul-data-volume:
    driver: local